# GraphQL схема для сервиса client-info
# Позволяет за один запрос получить все нужные данные о клиенте

type Client {
  id: ID!
  name: String
  age: Int
  documents: [Document]    # список документов клиента
  relatives: [Relative]    # список родственников клиента
}

type Document {
  id: ID!
  type: String
  number: String
  issueDate: String
  expiryDate: String
}

type Relative {
  id: ID!
  relationType: String
  name: String
  age: Int
}

type Query {
  """
  Получить информацию о клиенте по ID.
  В рамках одного запроса можно запросить любые поля клиента,
  включая связанные документы и родственников.
  """
  client(id: ID!): Client
}